### ISSUE TITLE
Notebook 02 has a broken link to the sample data

### ISSUE THREAD

**Issue by tcpekin** [pyxem/pyxem-demos#35]
After the import statement, the link to the google drive folder with the example data 404s.

**Comment by ricounet67** [comment]
Yes, the same for me. It states that the files are in the Trash

**Comment by dnjohnstone** [comment]
Sorry about that, I just moved things in to a single directory and forgot about that link!

Should be here: https://drive.google.com/drive/folders/11CV7_wkFIsOtDICOcil8Bo25fo0NlR9I

As an aside - if you're planning on using the template matching part of that code in general, the grid creation code in the main repository is not ideal. We're working on making that better, but if you tell me and @pc494 what crystal symmetries you care about we can try to send you solutions for those in particular.

**Comment by tcpekin** [comment]
Great, thanks a ton Duncan!
