### ISSUE TITLE
import rotation_list_stereographic does not work anymore

### ISSUE THREAD

**Issue by me2404** [pyxem/pyxem-demos#36]
This command does not work: from diffsims.utils.sim_utils import rotation_list_stereographic.

**Comment by pc494** [comment]
Hi,

This is a change introduced in version `0.10.1`, the new syntax is:

```
from diffsims.generators.rotation_list_generators import get_grid_streographic
rot_list_cubic = get_grid_streographic('cubic',10)
rot_list_hexagonal = get_grid_streographic('hexagonal',10)
```

*Note the typo in streographic; this patch fix that corrects this hasn't come out yet.

Let me know if that doesn't work :)
