### ISSUE TITLE
pyxem-demos 0.11.0

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/pyxem-demos#43]
Tidying up in advance of a v0.11.0 release has highlighted some issues with the demos as they stand, which need to be fixed before release:

- [x] demo-02 : the sub pixel refinement step is throwing an Error
- [x] demo-02 : plotting the vector matching results is throwing an Error
- [x] demo-06 : separate_learning_segments is throwing an Error for using a > comparison between a float and a None type object. (Odd because I don't think we changed this part of the code...)
- [x] demo-08 : plotting the final PDF i.e. pdf.plot() is throwing a dimensions error
- [x] demo-09 : we need to put the data in the Google drive (I don't have a copy of it)
- [x] demo-09 : Update formatting for consistency with other demos.

@pc494 @tinabe @JoonatanL @CSSFrancis - it would be much appreciated if you could each have a look at the issue above that corresponds to code you contributed significantly to.

**Comment by pc494** [comment]
I'll handle the two problems in demo-02.

**Comment by tinabe** [comment]
**demo-06:**
It seems that the error in demo-06 is caused by "max_size = None", which should be "max_size = np.inf" (defined a few lines earlier in the notebook). 

Two other things I noticed: 
- segments.py line 239 is "learning_segment = LearningSegment(segments, factors_of_segments)" but the arguments should be switched: "learning_segment = LearningSegment(factors = factors_of_segments, loadings = segments)" 
- the demo06 notebook: where NMF is done, "centre = 'variables'," could be deleted, since that arguments is not used there.

**Comment by dnjohnstone** [comment]
Thanks @tinabe - I'm making the changes to the demo notebook now, which is great, are you sure about the segments.py change and do you know if it's going to break anything? Could you make a PR for it, please?

**Comment by dnjohnstone** [comment]
The bug in demo 08 seems to be a bit more of an actual issue - I think it was introduced here: 

https://github.com/pyxem/pyxem/commit/6709e820e2a845b46705f95171e0b38d3cb8ccba#diff-c5e670a96adcf9cfc6ad7c475fb12476

@JoonatanL some insight on what it should be doing would be helpful... I think the issue is that the length of the signal axis changes in this operation and that doesn't happen properly with the use of deepcopy @ericpre might have something to say about this too...

**Comment by dnjohnstone** [comment]
Ok @pc494 I think we're at the point where it's now just fix demo 02 and then I'll do the 0.11.0 release

**Comment by pc494** [comment]
Sorry, missed this when it came in. Will be on it start of play tomorrow.

**Comment by pc494** [comment]
#44 should be the end of this set.
