### ISSUE TITLE
01 - Error running the new center_direct_beam routine

### ISSUE THREAD

**Issue by pc494** [pyxem/pyxem-demos#49]
`pxyem 0.13.0-rc.1.dev #(from pip)`

@magnunor would you mind seeing if you can replicate the following?

![demo01](https://user-images.githubusercontent.com/32455330/104035163-b876c580-51c9-11eb-9255-d8022d940aeb.png)

**Comment by magnunor** [comment]
Looking at this now. For demo 01 it is at least due to `half_square_width` in combination with the automatic rechunking pull request.

Making a fix for this.

**Comment by pc494** [comment]
Don't worry about the demo 06 bit, I'm not sure it's a code problem just yet.

**Comment by magnunor** [comment]
@pc494, the bug you saw in demo 01 will depend on the size of the dataset. For datasets smaller than 30 MiB the dataset will fit inside one chunk, avoiding the issue.

This has been fixed in https://github.com/pyxem/pyxem/pull/712

**Comment by pc494** [comment]
This was fine when I tested for #61, closing.
