### ISSUE TITLE
Broken cells in demo sheets

### ISSUE THREAD

**Issue by maclariz** [pyxem/pyxem-demos#59]
In https://github.com/pyxem/pyxem-demos/blob/master/01%20GaAs%20Nanowire%20-%20Data%20Inspection%20-%20Preprocessing%20-%20Unsupervised%20Machine%20Learning.ipynb

the following cells do not work:

from pyxem.generators.vdf_generator import VDFGenerator

dpc.find_peaks_interactive()

**Comment by pc494** [comment]
This is a bug within the repo, details at https://github.com/pyxem/pyxem/issues/742 - it should be fixed in a forthcoming patch release, I've updated the demos to inform users of the problem
