### ISSUE TITLE
Demo07 incompatible with pyxem0.13: get_azimuthal_integral

### ISSUE THREAD

**Issue by zhang-siyuan** [pyxem/pyxem-demos#69]
Following the jupyter notebook until:
integration2d = dp.get_azimuthal_integral2d(npt_rad=100, unit="pyxem")
1. npt_rad is now npt
2. after the easy fix
integration2d = dp.get_azimuthal_integral2d(npt=100, unit="pyxem")
would lead to: 
ValueError: ai property is not currently set

Same problem for get_azimuthal_integral1d

Suspect it has something to do with the lazy input, but the problem persists after changing
dp.unit="2th_deg"
or giving wavelength=2.5e-12 for dp.unit = "k_A^-1" (the unit in Demo7)

**Comment by pc494** [comment]
The relevant PR is #63

**Comment by pc494** [comment]
If somebody could check that #63 did indeed fix this that would be grand.

**Comment by zhang-siyuan** [comment]
@CSSFrancis Thank you so much! Your notebook provides a compatible solution and some very nice notes, highly appreciate!
@pc494 Yes, the fix works perfectly for me.

**Comment by pc494** [comment]
Great, I'll close the issue
