### ISSUE TITLE
Errors in tutorials

### ISSUE THREAD

**Issue by Oridrew** [pyxem/pyxem-demos#7]
Hi! I am trying to follow the tutorials and I got several errors:
**GaAs Nanowire**
In Produce virtual diffraction contrast images for all diffraction vectors
AttributeError: 'DiffractionVectors' object has no attribute 'get_vdf_images'

**SED Phase & Orientation Mapping**
In [164]:
AttributeError: 'ElectronDiffraction' object has no attribute 'set_calibration'

**SED Strain Mapping by Affine Transform**
In box [9] dp = hs.stack()
NameError: name 'hs' is not defined

**Comment by pc494** [comment]
I missed this, my apologies. I've just fixed the SED & Orientation Mapping error (#8).

`hs`
will always be hyperspy, and so you just need to add (at the top)
`import hyperspy.api as hs`

The GaAs nanowire bit is removed functionality (see https://github.com/pyxem/pyxem/commit/56977148e750dd7d1da323ae732482e6781987af) ~ I'll look into what might be best.
