### ISSUE TITLE
Reducing Data Size, Adding in Binder Links etc.

### ISSUE THREAD

**Issue by CSSFrancis** [pyxem/pyxem-demos#72]
At some point we moved from uploading the necessary datasets for the demos. I really like the idea of making binder links for each of the files and automating building documentation from the demos.   Github has pretty strict limits about not uploading a file that is larger than 100 mb but I think that we should think about if we can reduce the size of the example datasets by:

- Reducing the size of the scan (x,y)
- Bin the dataset (kx, ky)
- Reduce the bit depth

The problem datasets are:
- Demo 2 --> demo 2 already crops the dataset to a 12 mb dataset.
- Demo 6 --> Rebinning the data by a factor of 2 makes the dataset 15 mb instead of 250 (reduced by factor of 16). It also speeds up this notebook a fair amount. (@pc494 do you think that this should be okay)
- Demo 10 -->  @magnunor  I haven't looked at this dataset much but is there anyway to get this under 100 mb just as an example?  We can still have the ability to download the full dataset but the the sake of running it in binder a small dataset might be more useful just to give people the ability to run it in a web browser.  

I'll probably just try to go forward with this when I have time.  But let me know if anyone has any concerns.

**Comment by magnunor** [comment]
Good idea! It should be possible to create a dataset which is under 100 MB in Demo 10, and still hit the "learning aims" intended in the notebook. In fact, that is what is (almost) being done already, where it is cropped to reduce the processing times.

I have several magnetic STEM-DPC datasets, and some of them are probably more suited for being "reduced". Feel free to ping me after Wednesday 23., and I'll see if I can make the dataset.

**Comment by pc494** [comment]
I think demo 06 should be fine to be rebinned down.

**Comment by CSSFrancis** [comment]
Okay, I'll start trying to get those working in the next couple of days!

**Comment by CSSFrancis** [comment]
PR #76 should close this
