### ISSUE TITLE
02 GaAs Nanowire - Phase Mapping - Orientation Mapping not compatible with current pyxem release

### ISSUE THREAD

**Issue by uellue** [pyxem/pyxem-demos#82]
When I run the notebook 02 GaAs Nanowire - Phase Mapping - Orientation Mapping with pyxem 0.15.1 I get the following error message:

![image](https://github.com/pyxem/pyxem-demos/assets/25689052/c3f55b82-c9b4-4a32-ba4d-05251aff7d6b)

...and if I try one of the suggested alternatives:

![image](https://github.com/pyxem/pyxem-demos/assets/25689052/fc7446c6-f878-403d-ae72-ee3111b91f1f)

**Comment by CSSFrancis** [comment]
@uellue Running notebooks in the CI has been on my todo list for a little bit now but this shows exactly why it is important!

I'll see if I can track down the bug and get this fixed!
